// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: protoDefs/chat.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeqNum uint64 `protobuf:"varint,1,opt,name=seqNum,proto3" json:"seqNum,omitempty"`
	Hash   []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *Pin) Reset() {
	*x = Pin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDefs_chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pin) ProtoMessage() {}

func (x *Pin) ProtoReflect() protoreflect.Message {
	mi := &file_protoDefs_chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pin.ProtoReflect.Descriptor instead.
func (*Pin) Descriptor() ([]byte, []int) {
	return file_protoDefs_chat_proto_rawDescGZIP(), []int{0}
}

func (x *Pin) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *Pin) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Body   string `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Pins   []*Pin `protobuf:"bytes,3,rep,name=pins,proto3" json:"pins,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDefs_chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_protoDefs_chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_protoDefs_chat_proto_rawDescGZIP(), []int{1}
}

func (x *Msg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Msg) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Msg) GetPins() []*Pin {
	if x != nil {
		return x.Pins
	}
	return nil
}

type MsgWrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg    *Msg   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Hash   []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Sig    []byte `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	SeqNum uint64 `protobuf:"varint,4,opt,name=seqNum,proto3" json:"seqNum,omitempty"`
}

func (x *MsgWrap) Reset() {
	*x = MsgWrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDefs_chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgWrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgWrap) ProtoMessage() {}

func (x *MsgWrap) ProtoReflect() protoreflect.Message {
	mi := &file_protoDefs_chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgWrap.ProtoReflect.Descriptor instead.
func (*MsgWrap) Descriptor() ([]byte, []int) {
	return file_protoDefs_chat_proto_rawDescGZIP(), []int{2}
}

func (x *MsgWrap) GetMsg() *Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MsgWrap) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *MsgWrap) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *MsgWrap) GetSeqNum() uint64 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

type PutMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *MsgWrap `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PutMsgReq) Reset() {
	*x = PutMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDefs_chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMsgReq) ProtoMessage() {}

func (x *PutMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_protoDefs_chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMsgReq.ProtoReflect.Descriptor instead.
func (*PutMsgReq) Descriptor() ([]byte, []int) {
	return file_protoDefs_chat_proto_rawDescGZIP(), []int{3}
}

func (x *PutMsgReq) GetMsg() *MsgWrap {
	if x != nil {
		return x.Msg
	}
	return nil
}

type PutMsgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PutMsgResp) Reset() {
	*x = PutMsgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDefs_chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutMsgResp) ProtoMessage() {}

func (x *PutMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_protoDefs_chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutMsgResp.ProtoReflect.Descriptor instead.
func (*PutMsgResp) Descriptor() ([]byte, []int) {
	return file_protoDefs_chat_proto_rawDescGZIP(), []int{4}
}

type GetMsgsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (x *GetMsgsReq) Reset() {
	*x = GetMsgsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDefs_chat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMsgsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMsgsReq) ProtoMessage() {}

func (x *GetMsgsReq) ProtoReflect() protoreflect.Message {
	mi := &file_protoDefs_chat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMsgsReq.ProtoReflect.Descriptor instead.
func (*GetMsgsReq) Descriptor() ([]byte, []int) {
	return file_protoDefs_chat_proto_rawDescGZIP(), []int{5}
}

func (x *GetMsgsReq) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type GetMsgsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg *MsgWrap `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *GetMsgsResp) Reset() {
	*x = GetMsgsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDefs_chat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMsgsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMsgsResp) ProtoMessage() {}

func (x *GetMsgsResp) ProtoReflect() protoreflect.Message {
	mi := &file_protoDefs_chat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMsgsResp.ProtoReflect.Descriptor instead.
func (*GetMsgsResp) Descriptor() ([]byte, []int) {
	return file_protoDefs_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetMsgsResp) GetMsg() *MsgWrap {
	if x != nil {
		return x.Msg
	}
	return nil
}

// UserKey used for serializing pre-generated pub/priv keys.
type UserKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PrivKey []byte `protobuf:"bytes,2,opt,name=privKey,proto3" json:"privKey,omitempty"`
	PubKey  []byte `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
}

func (x *UserKey) Reset() {
	*x = UserKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDefs_chat_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserKey) ProtoMessage() {}

func (x *UserKey) ProtoReflect() protoreflect.Message {
	mi := &file_protoDefs_chat_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserKey.ProtoReflect.Descriptor instead.
func (*UserKey) Descriptor() ([]byte, []int) {
	return file_protoDefs_chat_proto_rawDescGZIP(), []int{7}
}

func (x *UserKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserKey) GetPrivKey() []byte {
	if x != nil {
		return x.PrivKey
	}
	return nil
}

func (x *UserKey) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

type ManyUserKeys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserKeys []*UserKey `protobuf:"bytes,1,rep,name=userKeys,proto3" json:"userKeys,omitempty"`
}

func (x *ManyUserKeys) Reset() {
	*x = ManyUserKeys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoDefs_chat_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManyUserKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManyUserKeys) ProtoMessage() {}

func (x *ManyUserKeys) ProtoReflect() protoreflect.Message {
	mi := &file_protoDefs_chat_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManyUserKeys.ProtoReflect.Descriptor instead.
func (*ManyUserKeys) Descriptor() ([]byte, []int) {
	return file_protoDefs_chat_proto_rawDescGZIP(), []int{8}
}

func (x *ManyUserKeys) GetUserKeys() []*UserKey {
	if x != nil {
		return x.UserKeys
	}
	return nil
}

var File_protoDefs_chat_proto protoreflect.FileDescriptor

var file_protoDefs_chat_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x65, 0x66, 0x73, 0x2f, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x68, 0x61, 0x74, 0x22, 0x31, 0x0a, 0x03,
	0x50, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22,
	0x50, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x12, 0x1d, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x50, 0x69, 0x6e, 0x52, 0x04, 0x70, 0x69, 0x6e,
	0x73, 0x22, 0x64, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x57, 0x72, 0x61, 0x70, 0x12, 0x1b, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x73, 0x65, 0x71, 0x4e, 0x75, 0x6d, 0x22, 0x2c, 0x0a, 0x09, 0x50, 0x75, 0x74, 0x4d, 0x73,
	0x67, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x73, 0x67, 0x57, 0x72, 0x61, 0x70,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x0c, 0x0a, 0x0a, 0x50, 0x75, 0x74, 0x4d, 0x73, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x24, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x73, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x2e, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x4d, 0x73, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x4d, 0x73, 0x67,
	0x57, 0x72, 0x61, 0x70, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x4f, 0x0a, 0x07, 0x55, 0x73, 0x65,
	0x72, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x76,
	0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x72, 0x69, 0x76, 0x4b,
	0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x22, 0x39, 0x0a, 0x0c, 0x4d, 0x61,
	0x6e, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x29, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x4b, 0x65, 0x79, 0x73, 0x32, 0x69, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x2d, 0x0a,
	0x06, 0x50, 0x75, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x0f, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x50,
	0x75, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e,
	0x50, 0x75, 0x74, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x73, 0x12, 0x10, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x73, 0x67, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x63, 0x68, 0x61, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoDefs_chat_proto_rawDescOnce sync.Once
	file_protoDefs_chat_proto_rawDescData = file_protoDefs_chat_proto_rawDesc
)

func file_protoDefs_chat_proto_rawDescGZIP() []byte {
	file_protoDefs_chat_proto_rawDescOnce.Do(func() {
		file_protoDefs_chat_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoDefs_chat_proto_rawDescData)
	})
	return file_protoDefs_chat_proto_rawDescData
}

var file_protoDefs_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protoDefs_chat_proto_goTypes = []interface{}{
	(*Pin)(nil),          // 0: chat.Pin
	(*Msg)(nil),          // 1: chat.Msg
	(*MsgWrap)(nil),      // 2: chat.MsgWrap
	(*PutMsgReq)(nil),    // 3: chat.PutMsgReq
	(*PutMsgResp)(nil),   // 4: chat.PutMsgResp
	(*GetMsgsReq)(nil),   // 5: chat.GetMsgsReq
	(*GetMsgsResp)(nil),  // 6: chat.GetMsgsResp
	(*UserKey)(nil),      // 7: chat.UserKey
	(*ManyUserKeys)(nil), // 8: chat.ManyUserKeys
}
var file_protoDefs_chat_proto_depIdxs = []int32{
	0, // 0: chat.Msg.pins:type_name -> chat.Pin
	1, // 1: chat.MsgWrap.msg:type_name -> chat.Msg
	2, // 2: chat.PutMsgReq.msg:type_name -> chat.MsgWrap
	2, // 3: chat.GetMsgsResp.msg:type_name -> chat.MsgWrap
	7, // 4: chat.ManyUserKeys.userKeys:type_name -> chat.UserKey
	3, // 5: chat.Chat.PutMsg:input_type -> chat.PutMsgReq
	5, // 6: chat.Chat.GetMsgs:input_type -> chat.GetMsgsReq
	4, // 7: chat.Chat.PutMsg:output_type -> chat.PutMsgResp
	6, // 8: chat.Chat.GetMsgs:output_type -> chat.GetMsgsResp
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_protoDefs_chat_proto_init() }
func file_protoDefs_chat_proto_init() {
	if File_protoDefs_chat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoDefs_chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDefs_chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDefs_chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgWrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDefs_chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDefs_chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutMsgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDefs_chat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMsgsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDefs_chat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMsgsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDefs_chat_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoDefs_chat_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManyUserKeys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoDefs_chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoDefs_chat_proto_goTypes,
		DependencyIndexes: file_protoDefs_chat_proto_depIdxs,
		MessageInfos:      file_protoDefs_chat_proto_msgTypes,
	}.Build()
	File_protoDefs_chat_proto = out.File
	file_protoDefs_chat_proto_rawDesc = nil
	file_protoDefs_chat_proto_goTypes = nil
	file_protoDefs_chat_proto_depIdxs = nil
}
