// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: rpc/chat.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatClient interface {
	PutMsg(ctx context.Context, in *PutMsgReq, opts ...grpc.CallOption) (*PutMsgResp, error)
	GetMsgs(ctx context.Context, in *GetMsgsReq, opts ...grpc.CallOption) (*GetMsgsResp, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) PutMsg(ctx context.Context, in *PutMsgReq, opts ...grpc.CallOption) (*PutMsgResp, error) {
	out := new(PutMsgResp)
	err := c.cc.Invoke(ctx, "/chat.Chat/PutMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetMsgs(ctx context.Context, in *GetMsgsReq, opts ...grpc.CallOption) (*GetMsgsResp, error) {
	out := new(GetMsgsResp)
	err := c.cc.Invoke(ctx, "/chat.Chat/GetMsgs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility
type ChatServer interface {
	PutMsg(context.Context, *PutMsgReq) (*PutMsgResp, error)
	GetMsgs(context.Context, *GetMsgsReq) (*GetMsgsResp, error)
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (UnimplementedChatServer) PutMsg(context.Context, *PutMsgReq) (*PutMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutMsg not implemented")
}
func (UnimplementedChatServer) GetMsgs(context.Context, *GetMsgsReq) (*GetMsgsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMsgs not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_PutMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).PutMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/PutMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).PutMsg(ctx, req.(*PutMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetMsgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMsgsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetMsgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/GetMsgs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetMsgs(ctx, req.(*GetMsgsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutMsg",
			Handler:    _Chat_PutMsg_Handler,
		},
		{
			MethodName: "GetMsgs",
			Handler:    _Chat_GetMsgs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/chat.proto",
}
