// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: rpc/photo_sharing.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPhotoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []byte `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *AddPhotoReq) Reset() {
	*x = AddPhotoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_photo_sharing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPhotoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPhotoReq) ProtoMessage() {}

func (x *AddPhotoReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_photo_sharing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPhotoReq.ProtoReflect.Descriptor instead.
func (*AddPhotoReq) Descriptor() ([]byte, []int) {
	return file_rpc_photo_sharing_proto_rawDescGZIP(), []int{0}
}

func (x *AddPhotoReq) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type AddPhotoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *AddPhotoResp) Reset() {
	*x = AddPhotoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_photo_sharing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPhotoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPhotoResp) ProtoMessage() {}

func (x *AddPhotoResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_photo_sharing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPhotoResp.ProtoReflect.Descriptor instead.
func (*AddPhotoResp) Descriptor() ([]byte, []int) {
	return file_rpc_photo_sharing_proto_rawDescGZIP(), []int{1}
}

func (x *AddPhotoResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListPhotosReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListPhotosReq) Reset() {
	*x = ListPhotosReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_photo_sharing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPhotosReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhotosReq) ProtoMessage() {}

func (x *ListPhotosReq) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_photo_sharing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhotosReq.ProtoReflect.Descriptor instead.
func (*ListPhotosReq) Descriptor() ([]byte, []int) {
	return file_rpc_photo_sharing_proto_rawDescGZIP(), []int{2}
}

func (x *ListPhotosReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListPhotosResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *ListPhotosResp) Reset() {
	*x = ListPhotosResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_photo_sharing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPhotosResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPhotosResp) ProtoMessage() {}

func (x *ListPhotosResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_photo_sharing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPhotosResp.ProtoReflect.Descriptor instead.
func (*ListPhotosResp) Descriptor() ([]byte, []int) {
	return file_rpc_photo_sharing_proto_rawDescGZIP(), []int{3}
}

func (x *ListPhotosResp) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

var File_rpc_photo_sharing_proto protoreflect.FileDescriptor

var file_rpc_photo_sharing_proto_rawDesc = []byte{
	0x0a, 0x17, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72,
	0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x5f, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x21, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x50,
	0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x22, 0x0a, 0x0c, 0x41,
	0x64, 0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22,
	0x23, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x26, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x68, 0x6f, 0x74,
	0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x32, 0x9c, 0x01, 0x0a,
	0x06, 0x53, 0x68, 0x61, 0x72, 0x65, 0x72, 0x12, 0x45, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x50, 0x68,
	0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72,
	0x69, 0x6e, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x2e,
	0x41, 0x64, 0x64, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x4b,
	0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x12, 0x1c, 0x2e, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1d, 0x2e, 0x70, 0x68, 0x6f,
	0x74, 0x6f, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x68, 0x6f, 0x74, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_photo_sharing_proto_rawDescOnce sync.Once
	file_rpc_photo_sharing_proto_rawDescData = file_rpc_photo_sharing_proto_rawDesc
)

func file_rpc_photo_sharing_proto_rawDescGZIP() []byte {
	file_rpc_photo_sharing_proto_rawDescOnce.Do(func() {
		file_rpc_photo_sharing_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_photo_sharing_proto_rawDescData)
	})
	return file_rpc_photo_sharing_proto_rawDescData
}

var file_rpc_photo_sharing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_photo_sharing_proto_goTypes = []interface{}{
	(*AddPhotoReq)(nil),    // 0: photo_sharing.AddPhotoReq
	(*AddPhotoResp)(nil),   // 1: photo_sharing.AddPhotoResp
	(*ListPhotosReq)(nil),  // 2: photo_sharing.ListPhotosReq
	(*ListPhotosResp)(nil), // 3: photo_sharing.ListPhotosResp
}
var file_rpc_photo_sharing_proto_depIdxs = []int32{
	0, // 0: photo_sharing.Sharer.AddPhoto:input_type -> photo_sharing.AddPhotoReq
	2, // 1: photo_sharing.Sharer.ListPhotos:input_type -> photo_sharing.ListPhotosReq
	1, // 2: photo_sharing.Sharer.AddPhoto:output_type -> photo_sharing.AddPhotoResp
	3, // 3: photo_sharing.Sharer.ListPhotos:output_type -> photo_sharing.ListPhotosResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_photo_sharing_proto_init() }
func file_rpc_photo_sharing_proto_init() {
	if File_rpc_photo_sharing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_photo_sharing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPhotoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_photo_sharing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPhotoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_photo_sharing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPhotosReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_photo_sharing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPhotosResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_photo_sharing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_photo_sharing_proto_goTypes,
		DependencyIndexes: file_rpc_photo_sharing_proto_depIdxs,
		MessageInfos:      file_rpc_photo_sharing_proto_msgTypes,
	}.Build()
	File_rpc_photo_sharing_proto = out.File
	file_rpc_photo_sharing_proto_rawDesc = nil
	file_rpc_photo_sharing_proto_goTypes = nil
	file_rpc_photo_sharing_proto_depIdxs = nil
}
