(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.crypto_prelude.
Require Export New.generatedproof.bytes.
Require Export New.generatedproof.github_com.goose_lang.std.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.advrpc.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.cryptoffi.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.hashchain.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.ktcore.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.merkle.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.safemarshal.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.server.
Require Export New.generatedproof.github_com.tchajed.marshal.
Require Export New.generatedproof.sync.
Require Export New.golang.theory.
Require Export New.code.github_com.sanjit_bhat.pav.auditor.

Set Default Proof Using "Type".

Module auditor.
Module Auditor.
Section def.

Context `{!heapGS Σ}.
Context {sem : go.Semantics}.
Context {package_sem' : auditor.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Auditor_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (auditor.Auditor.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "sk" ∷ l.[(auditor.Auditor.t), "sk"] ↦{dq} v.(auditor.Auditor.sk') ∗
      "serv" ∷ l.[(auditor.Auditor.t), "serv"] ↦{dq} v.(auditor.Auditor.serv') ∗
      "vrf" ∷ l.[(auditor.Auditor.t), "vrf"] ↦{dq} v.(auditor.Auditor.vrf') ∗
      "mu" ∷ l.[(auditor.Auditor.t), "mu"] ↦{dq} v.(auditor.Auditor.mu') ∗
      "hist" ∷ l.[(auditor.Auditor.t), "hist"] ↦{dq} v.(auditor.Auditor.hist') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Auditor_into_val_typed
   :
  IntoValTypedUnderlying (auditor.Auditor.t) (auditor.Auditorⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Auditor_access_load_sk l (v : (auditor.Auditor.t)) dq :
  AccessStrict
    (l.[(auditor.Auditor.t), "sk"] ↦{dq} (v.(auditor.Auditor.sk')))
    (l.[(auditor.Auditor.t), "sk"] ↦{dq} (v.(auditor.Auditor.sk')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Auditor_access_store_sk l (v : (auditor.Auditor.t)) sk' :
  AccessStrict
    (l.[(auditor.Auditor.t), "sk"] ↦ (v.(auditor.Auditor.sk')))
    (l.[(auditor.Auditor.t), "sk"] ↦ sk')
    (l ↦ v) (l ↦ (v <|(auditor.Auditor.sk') := sk'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Auditor_access_load_serv l (v : (auditor.Auditor.t)) dq :
  AccessStrict
    (l.[(auditor.Auditor.t), "serv"] ↦{dq} (v.(auditor.Auditor.serv')))
    (l.[(auditor.Auditor.t), "serv"] ↦{dq} (v.(auditor.Auditor.serv')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Auditor_access_store_serv l (v : (auditor.Auditor.t)) serv' :
  AccessStrict
    (l.[(auditor.Auditor.t), "serv"] ↦ (v.(auditor.Auditor.serv')))
    (l.[(auditor.Auditor.t), "serv"] ↦ serv')
    (l ↦ v) (l ↦ (v <|(auditor.Auditor.serv') := serv'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Auditor_access_load_vrf l (v : (auditor.Auditor.t)) dq :
  AccessStrict
    (l.[(auditor.Auditor.t), "vrf"] ↦{dq} (v.(auditor.Auditor.vrf')))
    (l.[(auditor.Auditor.t), "vrf"] ↦{dq} (v.(auditor.Auditor.vrf')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Auditor_access_store_vrf l (v : (auditor.Auditor.t)) vrf' :
  AccessStrict
    (l.[(auditor.Auditor.t), "vrf"] ↦ (v.(auditor.Auditor.vrf')))
    (l.[(auditor.Auditor.t), "vrf"] ↦ vrf')
    (l ↦ v) (l ↦ (v <|(auditor.Auditor.vrf') := vrf'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Auditor_access_load_mu l (v : (auditor.Auditor.t)) dq :
  AccessStrict
    (l.[(auditor.Auditor.t), "mu"] ↦{dq} (v.(auditor.Auditor.mu')))
    (l.[(auditor.Auditor.t), "mu"] ↦{dq} (v.(auditor.Auditor.mu')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Auditor_access_store_mu l (v : (auditor.Auditor.t)) mu' :
  AccessStrict
    (l.[(auditor.Auditor.t), "mu"] ↦ (v.(auditor.Auditor.mu')))
    (l.[(auditor.Auditor.t), "mu"] ↦ mu')
    (l ↦ v) (l ↦ (v <|(auditor.Auditor.mu') := mu'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance Auditor_access_load_hist l (v : (auditor.Auditor.t)) dq :
  AccessStrict
    (l.[(auditor.Auditor.t), "hist"] ↦{dq} (v.(auditor.Auditor.hist')))
    (l.[(auditor.Auditor.t), "hist"] ↦{dq} (v.(auditor.Auditor.hist')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Auditor_access_store_hist l (v : (auditor.Auditor.t)) hist' :
  AccessStrict
    (l.[(auditor.Auditor.t), "hist"] ↦ (v.(auditor.Auditor.hist')))
    (l.[(auditor.Auditor.t), "hist"] ↦ hist')
    (l ↦ v) (l ↦ (v <|(auditor.Auditor.hist') := hist'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Auditor.

Module history.
Section def.

Context `{!heapGS Σ}.
Context {sem : go.Semantics}.
Context {package_sem' : auditor.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance history_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (auditor.history.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "lastDig" ∷ l.[(auditor.history.t), "lastDig"] ↦{dq} v.(auditor.history.lastDig') ∗
      "startEp" ∷ l.[(auditor.history.t), "startEp"] ↦{dq} v.(auditor.history.startEp') ∗
      "epochs" ∷ l.[(auditor.history.t), "epochs"] ↦{dq} v.(auditor.history.epochs') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance history_into_val_typed
   :
  IntoValTypedUnderlying (auditor.history.t) (auditor.historyⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance history_access_load_lastDig l (v : (auditor.history.t)) dq :
  AccessStrict
    (l.[(auditor.history.t), "lastDig"] ↦{dq} (v.(auditor.history.lastDig')))
    (l.[(auditor.history.t), "lastDig"] ↦{dq} (v.(auditor.history.lastDig')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance history_access_store_lastDig l (v : (auditor.history.t)) lastDig' :
  AccessStrict
    (l.[(auditor.history.t), "lastDig"] ↦ (v.(auditor.history.lastDig')))
    (l.[(auditor.history.t), "lastDig"] ↦ lastDig')
    (l ↦ v) (l ↦ (v <|(auditor.history.lastDig') := lastDig'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance history_access_load_startEp l (v : (auditor.history.t)) dq :
  AccessStrict
    (l.[(auditor.history.t), "startEp"] ↦{dq} (v.(auditor.history.startEp')))
    (l.[(auditor.history.t), "startEp"] ↦{dq} (v.(auditor.history.startEp')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance history_access_store_startEp l (v : (auditor.history.t)) startEp' :
  AccessStrict
    (l.[(auditor.history.t), "startEp"] ↦ (v.(auditor.history.startEp')))
    (l.[(auditor.history.t), "startEp"] ↦ startEp')
    (l ↦ v) (l ↦ (v <|(auditor.history.startEp') := startEp'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance history_access_load_epochs l (v : (auditor.history.t)) dq :
  AccessStrict
    (l.[(auditor.history.t), "epochs"] ↦{dq} (v.(auditor.history.epochs')))
    (l.[(auditor.history.t), "epochs"] ↦{dq} (v.(auditor.history.epochs')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance history_access_store_epochs l (v : (auditor.history.t)) epochs' :
  AccessStrict
    (l.[(auditor.history.t), "epochs"] ↦ (v.(auditor.history.epochs')))
    (l.[(auditor.history.t), "epochs"] ↦ epochs')
    (l ↦ v) (l ↦ (v <|(auditor.history.epochs') := epochs'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End history.

Module serv.
Section def.

Context `{!heapGS Σ}.
Context {sem : go.Semantics}.
Context {package_sem' : auditor.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance serv_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (auditor.serv.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "cli" ∷ l.[(auditor.serv.t), "cli"] ↦{dq} v.(auditor.serv.cli') ∗
      "sigPk" ∷ l.[(auditor.serv.t), "sigPk"] ↦{dq} v.(auditor.serv.sigPk') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance serv_into_val_typed
   :
  IntoValTypedUnderlying (auditor.serv.t) (auditor.servⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance serv_access_load_cli l (v : (auditor.serv.t)) dq :
  AccessStrict
    (l.[(auditor.serv.t), "cli"] ↦{dq} (v.(auditor.serv.cli')))
    (l.[(auditor.serv.t), "cli"] ↦{dq} (v.(auditor.serv.cli')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance serv_access_store_cli l (v : (auditor.serv.t)) cli' :
  AccessStrict
    (l.[(auditor.serv.t), "cli"] ↦ (v.(auditor.serv.cli')))
    (l.[(auditor.serv.t), "cli"] ↦ cli')
    (l ↦ v) (l ↦ (v <|(auditor.serv.cli') := cli'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance serv_access_load_sigPk l (v : (auditor.serv.t)) dq :
  AccessStrict
    (l.[(auditor.serv.t), "sigPk"] ↦{dq} (v.(auditor.serv.sigPk')))
    (l.[(auditor.serv.t), "sigPk"] ↦{dq} (v.(auditor.serv.sigPk')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance serv_access_store_sigPk l (v : (auditor.serv.t)) sigPk' :
  AccessStrict
    (l.[(auditor.serv.t), "sigPk"] ↦ (v.(auditor.serv.sigPk')))
    (l.[(auditor.serv.t), "sigPk"] ↦ sigPk')
    (l ↦ v) (l ↦ (v <|(auditor.serv.sigPk') := sigPk'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End serv.

Module GetArg.
Section def.

Context `{!heapGS Σ}.
Context {sem : go.Semantics}.
Context {package_sem' : auditor.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance GetArg_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (auditor.GetArg.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Epoch" ∷ l.[(auditor.GetArg.t), "Epoch"] ↦{dq} v.(auditor.GetArg.Epoch') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance GetArg_into_val_typed
   :
  IntoValTypedUnderlying (auditor.GetArg.t) (auditor.GetArgⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance GetArg_access_load_Epoch l (v : (auditor.GetArg.t)) dq :
  AccessStrict
    (l.[(auditor.GetArg.t), "Epoch"] ↦{dq} (v.(auditor.GetArg.Epoch')))
    (l.[(auditor.GetArg.t), "Epoch"] ↦{dq} (v.(auditor.GetArg.Epoch')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance GetArg_access_store_Epoch l (v : (auditor.GetArg.t)) Epoch' :
  AccessStrict
    (l.[(auditor.GetArg.t), "Epoch"] ↦ (v.(auditor.GetArg.Epoch')))
    (l.[(auditor.GetArg.t), "Epoch"] ↦ Epoch')
    (l ↦ v) (l ↦ (v <|(auditor.GetArg.Epoch') := Epoch'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End GetArg.

Module SignedLink.
Section def.

Context `{!heapGS Σ}.
Context {sem : go.Semantics}.
Context {package_sem' : auditor.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance SignedLink_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (auditor.SignedLink.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "Link" ∷ l.[(auditor.SignedLink.t), "Link"] ↦{dq} v.(auditor.SignedLink.Link') ∗
      "ServSig" ∷ l.[(auditor.SignedLink.t), "ServSig"] ↦{dq} v.(auditor.SignedLink.ServSig') ∗
      "AdtrSig" ∷ l.[(auditor.SignedLink.t), "AdtrSig"] ↦{dq} v.(auditor.SignedLink.AdtrSig') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance SignedLink_into_val_typed
   :
  IntoValTypedUnderlying (auditor.SignedLink.t) (auditor.SignedLinkⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance SignedLink_access_load_Link l (v : (auditor.SignedLink.t)) dq :
  AccessStrict
    (l.[(auditor.SignedLink.t), "Link"] ↦{dq} (v.(auditor.SignedLink.Link')))
    (l.[(auditor.SignedLink.t), "Link"] ↦{dq} (v.(auditor.SignedLink.Link')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance SignedLink_access_store_Link l (v : (auditor.SignedLink.t)) Link' :
  AccessStrict
    (l.[(auditor.SignedLink.t), "Link"] ↦ (v.(auditor.SignedLink.Link')))
    (l.[(auditor.SignedLink.t), "Link"] ↦ Link')
    (l ↦ v) (l ↦ (v <|(auditor.SignedLink.Link') := Link'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance SignedLink_access_load_ServSig l (v : (auditor.SignedLink.t)) dq :
  AccessStrict
    (l.[(auditor.SignedLink.t), "ServSig"] ↦{dq} (v.(auditor.SignedLink.ServSig')))
    (l.[(auditor.SignedLink.t), "ServSig"] ↦{dq} (v.(auditor.SignedLink.ServSig')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance SignedLink_access_store_ServSig l (v : (auditor.SignedLink.t)) ServSig' :
  AccessStrict
    (l.[(auditor.SignedLink.t), "ServSig"] ↦ (v.(auditor.SignedLink.ServSig')))
    (l.[(auditor.SignedLink.t), "ServSig"] ↦ ServSig')
    (l ↦ v) (l ↦ (v <|(auditor.SignedLink.ServSig') := ServSig'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance SignedLink_access_load_AdtrSig l (v : (auditor.SignedLink.t)) dq :
  AccessStrict
    (l.[(auditor.SignedLink.t), "AdtrSig"] ↦{dq} (v.(auditor.SignedLink.AdtrSig')))
    (l.[(auditor.SignedLink.t), "AdtrSig"] ↦{dq} (v.(auditor.SignedLink.AdtrSig')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance SignedLink_access_store_AdtrSig l (v : (auditor.SignedLink.t)) AdtrSig' :
  AccessStrict
    (l.[(auditor.SignedLink.t), "AdtrSig"] ↦ (v.(auditor.SignedLink.AdtrSig')))
    (l.[(auditor.SignedLink.t), "AdtrSig"] ↦ AdtrSig')
    (l ↦ v) (l ↦ (v <|(auditor.SignedLink.AdtrSig') := AdtrSig'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End SignedLink.

Module SignedVrf.
Section def.

Context `{!heapGS Σ}.
Context {sem : go.Semantics}.
Context {package_sem' : auditor.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance SignedVrf_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (auditor.SignedVrf.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "VrfPk" ∷ l.[(auditor.SignedVrf.t), "VrfPk"] ↦{dq} v.(auditor.SignedVrf.VrfPk') ∗
      "ServSig" ∷ l.[(auditor.SignedVrf.t), "ServSig"] ↦{dq} v.(auditor.SignedVrf.ServSig') ∗
      "AdtrSig" ∷ l.[(auditor.SignedVrf.t), "AdtrSig"] ↦{dq} v.(auditor.SignedVrf.AdtrSig') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance SignedVrf_into_val_typed
   :
  IntoValTypedUnderlying (auditor.SignedVrf.t) (auditor.SignedVrfⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance SignedVrf_access_load_VrfPk l (v : (auditor.SignedVrf.t)) dq :
  AccessStrict
    (l.[(auditor.SignedVrf.t), "VrfPk"] ↦{dq} (v.(auditor.SignedVrf.VrfPk')))
    (l.[(auditor.SignedVrf.t), "VrfPk"] ↦{dq} (v.(auditor.SignedVrf.VrfPk')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance SignedVrf_access_store_VrfPk l (v : (auditor.SignedVrf.t)) VrfPk' :
  AccessStrict
    (l.[(auditor.SignedVrf.t), "VrfPk"] ↦ (v.(auditor.SignedVrf.VrfPk')))
    (l.[(auditor.SignedVrf.t), "VrfPk"] ↦ VrfPk')
    (l ↦ v) (l ↦ (v <|(auditor.SignedVrf.VrfPk') := VrfPk'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance SignedVrf_access_load_ServSig l (v : (auditor.SignedVrf.t)) dq :
  AccessStrict
    (l.[(auditor.SignedVrf.t), "ServSig"] ↦{dq} (v.(auditor.SignedVrf.ServSig')))
    (l.[(auditor.SignedVrf.t), "ServSig"] ↦{dq} (v.(auditor.SignedVrf.ServSig')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance SignedVrf_access_store_ServSig l (v : (auditor.SignedVrf.t)) ServSig' :
  AccessStrict
    (l.[(auditor.SignedVrf.t), "ServSig"] ↦ (v.(auditor.SignedVrf.ServSig')))
    (l.[(auditor.SignedVrf.t), "ServSig"] ↦ ServSig')
    (l ↦ v) (l ↦ (v <|(auditor.SignedVrf.ServSig') := ServSig'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance SignedVrf_access_load_AdtrSig l (v : (auditor.SignedVrf.t)) dq :
  AccessStrict
    (l.[(auditor.SignedVrf.t), "AdtrSig"] ↦{dq} (v.(auditor.SignedVrf.AdtrSig')))
    (l.[(auditor.SignedVrf.t), "AdtrSig"] ↦{dq} (v.(auditor.SignedVrf.AdtrSig')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance SignedVrf_access_store_AdtrSig l (v : (auditor.SignedVrf.t)) AdtrSig' :
  AccessStrict
    (l.[(auditor.SignedVrf.t), "AdtrSig"] ↦ (v.(auditor.SignedVrf.AdtrSig')))
    (l.[(auditor.SignedVrf.t), "AdtrSig"] ↦ AdtrSig')
    (l ↦ v) (l ↦ (v <|(auditor.SignedVrf.AdtrSig') := AdtrSig'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End SignedVrf.

Module GetReply.
Section def.

Context `{!heapGS Σ}.
Context {sem : go.Semantics}.
Context {package_sem' : auditor.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance GetReply_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (auditor.GetReply.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "StartEp" ∷ l.[(auditor.GetReply.t), "StartEp"] ↦{dq} v.(auditor.GetReply.StartEp') ∗
      "StartLink" ∷ l.[(auditor.GetReply.t), "StartLink"] ↦{dq} v.(auditor.GetReply.StartLink') ∗
      "CurrLink" ∷ l.[(auditor.GetReply.t), "CurrLink"] ↦{dq} v.(auditor.GetReply.CurrLink') ∗
      "Vrf" ∷ l.[(auditor.GetReply.t), "Vrf"] ↦{dq} v.(auditor.GetReply.Vrf') ∗
      "Err" ∷ l.[(auditor.GetReply.t), "Err"] ↦{dq} v.(auditor.GetReply.Err') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance GetReply_into_val_typed
   :
  IntoValTypedUnderlying (auditor.GetReply.t) (auditor.GetReplyⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance GetReply_access_load_StartEp l (v : (auditor.GetReply.t)) dq :
  AccessStrict
    (l.[(auditor.GetReply.t), "StartEp"] ↦{dq} (v.(auditor.GetReply.StartEp')))
    (l.[(auditor.GetReply.t), "StartEp"] ↦{dq} (v.(auditor.GetReply.StartEp')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance GetReply_access_store_StartEp l (v : (auditor.GetReply.t)) StartEp' :
  AccessStrict
    (l.[(auditor.GetReply.t), "StartEp"] ↦ (v.(auditor.GetReply.StartEp')))
    (l.[(auditor.GetReply.t), "StartEp"] ↦ StartEp')
    (l ↦ v) (l ↦ (v <|(auditor.GetReply.StartEp') := StartEp'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance GetReply_access_load_StartLink l (v : (auditor.GetReply.t)) dq :
  AccessStrict
    (l.[(auditor.GetReply.t), "StartLink"] ↦{dq} (v.(auditor.GetReply.StartLink')))
    (l.[(auditor.GetReply.t), "StartLink"] ↦{dq} (v.(auditor.GetReply.StartLink')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance GetReply_access_store_StartLink l (v : (auditor.GetReply.t)) StartLink' :
  AccessStrict
    (l.[(auditor.GetReply.t), "StartLink"] ↦ (v.(auditor.GetReply.StartLink')))
    (l.[(auditor.GetReply.t), "StartLink"] ↦ StartLink')
    (l ↦ v) (l ↦ (v <|(auditor.GetReply.StartLink') := StartLink'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance GetReply_access_load_CurrLink l (v : (auditor.GetReply.t)) dq :
  AccessStrict
    (l.[(auditor.GetReply.t), "CurrLink"] ↦{dq} (v.(auditor.GetReply.CurrLink')))
    (l.[(auditor.GetReply.t), "CurrLink"] ↦{dq} (v.(auditor.GetReply.CurrLink')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance GetReply_access_store_CurrLink l (v : (auditor.GetReply.t)) CurrLink' :
  AccessStrict
    (l.[(auditor.GetReply.t), "CurrLink"] ↦ (v.(auditor.GetReply.CurrLink')))
    (l.[(auditor.GetReply.t), "CurrLink"] ↦ CurrLink')
    (l ↦ v) (l ↦ (v <|(auditor.GetReply.CurrLink') := CurrLink'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance GetReply_access_load_Vrf l (v : (auditor.GetReply.t)) dq :
  AccessStrict
    (l.[(auditor.GetReply.t), "Vrf"] ↦{dq} (v.(auditor.GetReply.Vrf')))
    (l.[(auditor.GetReply.t), "Vrf"] ↦{dq} (v.(auditor.GetReply.Vrf')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance GetReply_access_store_Vrf l (v : (auditor.GetReply.t)) Vrf' :
  AccessStrict
    (l.[(auditor.GetReply.t), "Vrf"] ↦ (v.(auditor.GetReply.Vrf')))
    (l.[(auditor.GetReply.t), "Vrf"] ↦ Vrf')
    (l ↦ v) (l ↦ (v <|(auditor.GetReply.Vrf') := Vrf'|>))%I.
Proof. solve_pointsto_access_struct. Qed.
#[global] Instance GetReply_access_load_Err l (v : (auditor.GetReply.t)) dq :
  AccessStrict
    (l.[(auditor.GetReply.t), "Err"] ↦{dq} (v.(auditor.GetReply.Err')))
    (l.[(auditor.GetReply.t), "Err"] ↦{dq} (v.(auditor.GetReply.Err')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance GetReply_access_store_Err l (v : (auditor.GetReply.t)) Err' :
  AccessStrict
    (l.[(auditor.GetReply.t), "Err"] ↦ (v.(auditor.GetReply.Err')))
    (l.[(auditor.GetReply.t), "Err"] ↦ Err')
    (l ↦ v) (l ↦ (v <|(auditor.GetReply.Err') := Err'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End GetReply.

End auditor.
