(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.proof_prelude.
Require Export New.manualproof.github_com.sanjit_bhat.pav.cryptoffi.
Require Export New.generatedproof.crypto.ed25519.
Require Export New.golang.theory.
Require Export New.code.github_com.sanjit_bhat.pav.cryptoffi.

Set Default Proof Using "Type".

Module cryptoffi.
Module Hasher.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cryptoffi.Assumptions}.

Local Set Default Proof Using "All".

#[global]Program Instance Hasher_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cryptoffi.Hasher.t) :=
  {|
    typed_pointsto_def l v dq :=
      (
      "b" ∷ l.[(cryptoffi.Hasher.t), "b"] ↦{dq} v.(cryptoffi.Hasher.b') ∗
      "_" ∷ True
      )%I
  |}.
Final Obligation. solve_typed_pointsto_agree. Qed.

#[global] Instance Hasher_into_val_typed
   :
  IntoValTypedUnderlying (cryptoffi.Hasher.t) (cryptoffi.Hasherⁱᵐᵖˡ).
Proof. solve_into_val_typed_struct. Qed.
#[global] Instance Hasher_access_load_b l (v : (cryptoffi.Hasher.t)) dq :
  AccessStrict
    (l.[(cryptoffi.Hasher.t), "b"] ↦{dq} (v.(cryptoffi.Hasher.b')))
    (l.[(cryptoffi.Hasher.t), "b"] ↦{dq} (v.(cryptoffi.Hasher.b')))
    (l ↦{dq} v) (l ↦{dq} v)%I.
Proof. solve_pointsto_access_struct. Qed.

#[global] Instance Hasher_access_store_b l (v : (cryptoffi.Hasher.t)) b' :
  AccessStrict
    (l.[(cryptoffi.Hasher.t), "b"] ↦ (v.(cryptoffi.Hasher.b')))
    (l.[(cryptoffi.Hasher.t), "b"] ↦ b')
    (l ↦ v) (l ↦ (v <|(cryptoffi.Hasher.b') := b'|>))%I.
Proof. solve_pointsto_access_struct. Qed.

End def.
End Hasher.

Module SigPrivateKey.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cryptoffi.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance SigPrivateKey_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cryptoffi.SigPrivateKey.t). Admitted.

#[global] Instance SigPrivateKey_into_val_typed
   :
  IntoValTypedUnderlying (cryptoffi.SigPrivateKey.t) (cryptoffi.SigPrivateKeyⁱᵐᵖˡ).
Proof. Admitted.

End def.
End SigPrivateKey.

Module VrfPrivateKey.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cryptoffi.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance VrfPrivateKey_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cryptoffi.VrfPrivateKey.t). Admitted.

#[global] Instance VrfPrivateKey_into_val_typed
   :
  IntoValTypedUnderlying (cryptoffi.VrfPrivateKey.t) (cryptoffi.VrfPrivateKeyⁱᵐᵖˡ).
Proof. Admitted.

End def.
End VrfPrivateKey.

Module VrfPublicKey.
Section def.

Context `{hG: heapGS Σ, !ffi_semantics _ _}.
Context {sem : go.Semantics}.
Context {package_sem' : cryptoffi.Assumptions}.

Local Set Default Proof Using "All".

#[global] Instance VrfPublicKey_typed_pointsto  :
  TypedPointsto (Σ:=Σ) (cryptoffi.VrfPublicKey.t). Admitted.

#[global] Instance VrfPublicKey_into_val_typed
   :
  IntoValTypedUnderlying (cryptoffi.VrfPublicKey.t) (cryptoffi.VrfPublicKeyⁱᵐᵖˡ).
Proof. Admitted.

End def.
End VrfPublicKey.

End cryptoffi.
