(* autogenerated from github.com/sanjit-bhat/pav/cryptoffi *)
Require Export New.code.crypto.ed25519.
From New.golang Require Import defn.
Module pkg_id.
Definition cryptoffi : go_string := "github.com/sanjit-bhat/pav/cryptoffi".

End pkg_id.
Export pkg_id.
Module cryptoffi.

Definition Hasher {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/sanjit-bhat/pav/cryptoffi.Hasher"%go [].

#[global] Opaque Hasher.

Definition SigPrivateKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/sanjit-bhat/pav/cryptoffi.SigPrivateKey"%go [].

#[global] Opaque SigPrivateKey.

Definition SigPublicKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/sanjit-bhat/pav/cryptoffi.SigPublicKey"%go [].

#[global] Opaque SigPublicKey.

Definition VrfPrivateKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/sanjit-bhat/pav/cryptoffi.VrfPrivateKey"%go [].

#[global] Opaque VrfPrivateKey.

Definition VrfPublicKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/sanjit-bhat/pav/cryptoffi.VrfPublicKey"%go [].

#[global] Opaque VrfPublicKey.

Axiom Hasherⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom SigPrivateKeyⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom VrfPrivateKeyⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom VrfPublicKeyⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Definition HashLen {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 32).

Definition NewHasher {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi.NewHasher"%go.

Definition SigGenerateKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi.SigGenerateKey"%go.

Definition VrfGenerateKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi.VrfGenerateKey"%go.

Definition VrfPublicKeyEncode {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi.VrfPublicKeyEncode"%go.

Definition VrfPublicKeyDecode {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi.VrfPublicKeyDecode"%go.

Definition RandBytes {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi.RandBytes"%go.

#[global] Instance info' : PkgInfo pkg_id.cryptoffi :=
{|
  pkg_imported_pkgs := [code.crypto.ed25519.pkg_id.ed25519]
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.cryptoffi (λ: <>,
      exception_do (do:  (ed25519.initialize' #()))
      ).

Module Hasher.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End Hasher.

Class Hasher_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Hasher_type_repr  :: go.TypeReprUnderlying Hasherⁱᵐᵖˡ Hasher.t;
  #[global] Hasher_underlying :: (Hasher) <u (Hasherⁱᵐᵖˡ);
  #[global] Hasherⁱᵐᵖˡ_underlying :: (Hasherⁱᵐᵖˡ) ↓u (Hasherⁱᵐᵖˡ);
}.

Module SigPrivateKey.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SigPrivateKey.

Class SigPrivateKey_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SigPrivateKey_type_repr  :: go.TypeReprUnderlying SigPrivateKeyⁱᵐᵖˡ SigPrivateKey.t;
  #[global] SigPrivateKey_underlying :: (SigPrivateKey) <u (SigPrivateKeyⁱᵐᵖˡ);
  #[global] SigPrivateKeyⁱᵐᵖˡ_underlying :: (SigPrivateKeyⁱᵐᵖˡ) ↓u (SigPrivateKeyⁱᵐᵖˡ);
}.

Module SigPublicKey.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Definition t : Type := ed25519.PublicKey.t.
End def.
End SigPublicKey.

Definition SigPublicKeyⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := ed25519.PublicKey.

Class SigPublicKey_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SigPublicKey_underlying :: (SigPublicKey) <u (SigPublicKeyⁱᵐᵖˡ);
}.

Module VrfPrivateKey.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End VrfPrivateKey.

Class VrfPrivateKey_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] VrfPrivateKey_type_repr  :: go.TypeReprUnderlying VrfPrivateKeyⁱᵐᵖˡ VrfPrivateKey.t;
  #[global] VrfPrivateKey_underlying :: (VrfPrivateKey) <u (VrfPrivateKeyⁱᵐᵖˡ);
  #[global] VrfPrivateKeyⁱᵐᵖˡ_underlying :: (VrfPrivateKeyⁱᵐᵖˡ) ↓u (VrfPrivateKeyⁱᵐᵖˡ);
}.

Module VrfPublicKey.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End VrfPublicKey.

Class VrfPublicKey_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] VrfPublicKey_type_repr  :: go.TypeReprUnderlying VrfPublicKeyⁱᵐᵖˡ VrfPublicKey.t;
  #[global] VrfPublicKey_underlying :: (VrfPublicKey) <u (VrfPublicKeyⁱᵐᵖˡ);
  #[global] VrfPublicKeyⁱᵐᵖˡ_underlying :: (VrfPublicKeyⁱᵐᵖˡ) ↓u (VrfPublicKeyⁱᵐᵖˡ);
}.

Class Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Hasher_instance :: Hasher_Assumptions;
  #[global] SigPrivateKey_instance :: SigPrivateKey_Assumptions;
  #[global] SigPublicKey_instance :: SigPublicKey_Assumptions;
  #[global] VrfPrivateKey_instance :: VrfPrivateKey_Assumptions;
  #[global] VrfPublicKey_instance :: VrfPublicKey_Assumptions;
  #[global] import_ed25519_Assumption :: ed25519.Assumptions;
}.
End cryptoffi.
