(* autogenerated from github.com/sanjit-bhat/pav/alicebob *)
Require Export New.code.bytes.
Require Export New.code.time.
Require Export New.code.github_com.goose_lang.primitive.
Require Export New.code.github_com.goose_lang.std.
Require Export New.code.github_com.sanjit_bhat.pav.auditor.
Require Export New.code.github_com.sanjit_bhat.pav.client.
Require Export New.code.github_com.sanjit_bhat.pav.cryptoffi.
Require Export New.code.github_com.sanjit_bhat.pav.ktcore.
Require Export New.code.github_com.sanjit_bhat.pav.server.
From New.golang Require Import defn.
From New Require Import crypto_prelude.
Module pkg_id.
Definition alicebob : go_string := "github.com/sanjit-bhat/pav/alicebob".

End pkg_id.
Export pkg_id.
Module alicebob.

Definition aliceUid {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 0).

Definition bobUid {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 1).

Definition epochTime {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 1000000).

Definition testAliceBob {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/alicebob.testAliceBob"%go.

(* go: alicebob.go:22:6 *)
Definition testAliceBobⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "servAddr" "servGood" "adtrAddrs",
    exception_do (let: "adtrAddrs" := (GoAlloc (go.SliceType go.uint64) "adtrAddrs") in
    let: "servGood" := (GoAlloc go.bool "servGood") in
    let: "servAddr" := (GoAlloc go.uint64 "servAddr") in
    let: "servPk" := (GoAlloc cryptoffi.SigPublicKey (GoZeroVal cryptoffi.SigPublicKey #())) in
    let: "serv" := (GoAlloc (go.PointerType server.Server) (GoZeroVal (go.PointerType server.Server) #())) in
    let: ("$ret0", "$ret1") := (let: "$a0" := epochTime in
    (FuncResolve server.New [] #()) "$a0") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    do:  ("serv" <-[go.PointerType server.Server] "$r0");;;
    do:  ("servPk" <-[cryptoffi.SigPublicKey] "$r1");;;
    do:  (let: "$a0" := (![go.uint64] "servAddr") in
    (MethodResolve (go.PointerType advrpc.Server) "Serve"%go (let: "$a0" := (![go.PointerType server.Server] "serv") in
    (FuncResolve server.NewRpcServer [] #()) "$a0")) "$a0");;;
    do:  (let: "$a0" := time.Millisecond in
    (FuncResolve time.Sleep [] #()) "$a0");;;
    let: "err" := (GoAlloc ktcore.Blame (GoZeroVal ktcore.Blame #())) in
    let: "ep" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
    let: "alice" := (GoAlloc (go.PointerType client.Client) (GoZeroVal (go.PointerType client.Client) #())) in
    let: (("$ret0", "$ret1"), "$ret2") := (let: "$a0" := aliceUid in
    let: "$a1" := (![go.uint64] "servAddr") in
    let: "$a2" := (![cryptoffi.SigPublicKey] "servPk") in
    (FuncResolve client.New [] #()) "$a0" "$a1" "$a2") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    let: "$r2" := "$ret2" in
    do:  ("alice" <-[go.PointerType client.Client] "$r0");;;
    do:  ("ep" <-[go.uint64] "$r1");;;
    do:  ("err" <-[ktcore.Blame] "$r2");;;
    do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    do:  (let: "$a0" := ((![go.uint64] "ep") =⟨go.uint64⟩ #(W64 0)) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    let: "bob" := (GoAlloc (go.PointerType client.Client) (GoZeroVal (go.PointerType client.Client) #())) in
    let: (("$ret0", "$ret1"), "$ret2") := (let: "$a0" := bobUid in
    let: "$a1" := (![go.uint64] "servAddr") in
    let: "$a2" := (![cryptoffi.SigPublicKey] "servPk") in
    (FuncResolve client.New [] #()) "$a0" "$a1" "$a2") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    let: "$r2" := "$ret2" in
    do:  ("bob" <-[go.PointerType client.Client] "$r0");;;
    do:  ("ep" <-[go.uint64] "$r1");;;
    do:  ("err" <-[ktcore.Blame] "$r2");;;
    do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    do:  (let: "$a0" := ((![go.uint64] "ep") =⟨go.uint64⟩ #(W64 0)) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    let: "bobHasPk0" := (GoAlloc go.bool (GoZeroVal go.bool #())) in
    let: ((("$ret0", "$ret1"), "$ret2"), "$ret3") := (let: "$a0" := aliceUid in
    (MethodResolve (go.PointerType client.Client) "Get"%go (![go.PointerType client.Client] "bob")) "$a0") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    let: "$r2" := "$ret2" in
    let: "$r3" := "$ret3" in
    do:  ("ep" <-[go.uint64] "$r0");;;
    do:  ("bobHasPk0" <-[go.bool] "$r1");;;
    do:  "$r2";;;
    do:  ("err" <-[ktcore.Blame] "$r3");;;
    do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    do:  (let: "$a0" := ((![go.uint64] "ep") =⟨go.uint64⟩ #(W64 0)) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    let: "adtr1" := (GoAlloc (go.PointerType auditor.Auditor) (GoZeroVal (go.PointerType auditor.Auditor) #())) in
    let: "adtr0" := (GoAlloc (go.PointerType auditor.Auditor) (GoZeroVal (go.PointerType auditor.Auditor) #())) in
    let: "adtr1Pk" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    let: "adtr0Pk" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    (if: (⟨go.bool⟩! (![go.bool] "servGood"))
    then
      let: (("$ret0", "$ret1"), "$ret2") := (let: "$a0" := (![go.uint64] "servAddr") in
      let: "$a1" := (![cryptoffi.SigPublicKey] "servPk") in
      (FuncResolve auditor.New [] #()) "$a0" "$a1") in
      let: "$r0" := "$ret0" in
      let: "$r1" := "$ret1" in
      let: "$r2" := "$ret2" in
      do:  ("adtr0" <-[go.PointerType auditor.Auditor] "$r0");;;
      do:  ("adtr0Pk" <-[go.SliceType go.byte] "$r1");;;
      do:  ("err" <-[ktcore.Blame] "$r2");;;
      do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      let: (("$ret0", "$ret1"), "$ret2") := (let: "$a0" := (![go.uint64] "servAddr") in
      let: "$a1" := (![cryptoffi.SigPublicKey] "servPk") in
      (FuncResolve auditor.New [] #()) "$a0" "$a1") in
      let: "$r0" := "$ret0" in
      let: "$r1" := "$ret1" in
      let: "$r2" := "$ret2" in
      do:  ("adtr1" <-[go.PointerType auditor.Auditor] "$r0");;;
      do:  ("adtr1Pk" <-[go.SliceType go.byte] "$r1");;;
      do:  ("err" <-[ktcore.Blame] "$r2");;;
      do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      do:  (let: "$a0" := (![go.uint64] (IndexRef (go.SliceType go.uint64) (![go.SliceType go.uint64] "adtrAddrs", #(W64 0)))) in
      (MethodResolve (go.PointerType advrpc.Server) "Serve"%go (let: "$a0" := (![go.PointerType auditor.Auditor] "adtr0") in
      (FuncResolve auditor.NewRpcAuditor [] #()) "$a0")) "$a0");;;
      do:  (let: "$a0" := (![go.uint64] (IndexRef (go.SliceType go.uint64) (![go.SliceType go.uint64] "adtrAddrs", #(W64 1)))) in
      (MethodResolve (go.PointerType advrpc.Server) "Serve"%go (let: "$a0" := (![go.PointerType auditor.Auditor] "adtr1") in
      (FuncResolve auditor.NewRpcAuditor [] #()) "$a0")) "$a0");;;
      do:  (let: "$a0" := time.Millisecond in
      (FuncResolve time.Sleep [] #()) "$a0")
    else do:  #());;;
    let: "alicePk1" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    let: "$r0" := (let: "$a0" := #(W64 32) in
    (FuncResolve cryptoffi.RandBytes [] #()) "$a0") in
    do:  ("alicePk1" <-[go.SliceType go.byte] "$r0");;;
    do:  (let: "$a0" := (![go.SliceType go.byte] "alicePk1") in
    (MethodResolve (go.PointerType client.Client) "Put"%go (![go.PointerType client.Client] "alice")) "$a0");;;
    do:  (let: "$a0" := (#(W64 2) *⟨time.Duration⟩ epochTime) in
    (FuncResolve time.Sleep [] #()) "$a0");;;
    let: "isChanged" := (GoAlloc go.bool (GoZeroVal go.bool #())) in
    let: (("$ret0", "$ret1"), "$ret2") := ((MethodResolve (go.PointerType client.Client) "SelfMon"%go (![go.PointerType client.Client] "alice")) #()) in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    let: "$r2" := "$ret2" in
    do:  ("ep" <-[go.uint64] "$r0");;;
    do:  ("isChanged" <-[go.bool] "$r1");;;
    do:  ("err" <-[ktcore.Blame] "$r2");;;
    do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    do:  (let: "$a0" := ((![go.uint64] "ep") =⟨go.uint64⟩ #(W64 1)) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    do:  (let: "$a0" := (![go.bool] "isChanged") in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    let: "bobPk1" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    let: "bobHasPk1" := (GoAlloc go.bool (GoZeroVal go.bool #())) in
    let: ((("$ret0", "$ret1"), "$ret2"), "$ret3") := (let: "$a0" := aliceUid in
    (MethodResolve (go.PointerType client.Client) "Get"%go (![go.PointerType client.Client] "bob")) "$a0") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    let: "$r2" := "$ret2" in
    let: "$r3" := "$ret3" in
    do:  ("ep" <-[go.uint64] "$r0");;;
    do:  ("bobHasPk1" <-[go.bool] "$r1");;;
    do:  ("bobPk1" <-[go.SliceType go.byte] "$r2");;;
    do:  ("err" <-[ktcore.Blame] "$r3");;;
    do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    do:  (let: "$a0" := ((![go.uint64] "ep") =⟨go.uint64⟩ #(W64 1)) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    (if: (⟨go.bool⟩! (![go.bool] "servGood"))
    then
      do:  ((MethodResolve (go.PointerType auditor.Auditor) "Update"%go (![go.PointerType auditor.Auditor] "adtr0")) #());;;
      do:  ((MethodResolve (go.PointerType auditor.Auditor) "Update"%go (![go.PointerType auditor.Auditor] "adtr1")) #());;;
      let: "startEp" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
      let: ((("$ret0", "$ret1"), "$ret2"), "$ret3") := (let: "$a0" := (![go.uint64] (IndexRef (go.SliceType go.uint64) (![go.SliceType go.uint64] "adtrAddrs", #(W64 0)))) in
      let: "$a1" := (![go.SliceType go.byte] "adtr0Pk") in
      (MethodResolve (go.PointerType client.Client) "Audit"%go (![go.PointerType client.Client] "alice")) "$a0" "$a1") in
      let: "$r0" := "$ret0" in
      let: "$r1" := "$ret1" in
      let: "$r2" := "$ret2" in
      let: "$r3" := "$ret3" in
      do:  ("startEp" <-[go.uint64] "$r0");;;
      do:  ("ep" <-[go.uint64] "$r1");;;
      do:  ("err" <-[ktcore.Blame] "$r2");;;
      do:  "$r3";;;
      do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      do:  (let: "$a0" := ((![go.uint64] "startEp") =⟨go.uint64⟩ #(W64 0)) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      do:  (let: "$a0" := ((![go.uint64] "ep") =⟨go.uint64⟩ #(W64 1)) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      let: ((("$ret0", "$ret1"), "$ret2"), "$ret3") := (let: "$a0" := (![go.uint64] (IndexRef (go.SliceType go.uint64) (![go.SliceType go.uint64] "adtrAddrs", #(W64 1)))) in
      let: "$a1" := (![go.SliceType go.byte] "adtr1Pk") in
      (MethodResolve (go.PointerType client.Client) "Audit"%go (![go.PointerType client.Client] "bob")) "$a0" "$a1") in
      let: "$r0" := "$ret0" in
      let: "$r1" := "$ret1" in
      let: "$r2" := "$ret2" in
      let: "$r3" := "$ret3" in
      do:  ("startEp" <-[go.uint64] "$r0");;;
      do:  ("ep" <-[go.uint64] "$r1");;;
      do:  ("err" <-[ktcore.Blame] "$r2");;;
      do:  "$r3";;;
      do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      do:  (let: "$a0" := ((![go.uint64] "startEp") =⟨go.uint64⟩ #(W64 0)) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      do:  (let: "$a0" := ((![go.uint64] "ep") =⟨go.uint64⟩ #(W64 1)) in
      (FuncResolve primitive.Assume [] #()) "$a0")
    else do:  #());;;
    let: "adtr2" := (GoAlloc (go.PointerType auditor.Auditor) (GoZeroVal (go.PointerType auditor.Auditor) #())) in
    let: "adtr2Pk" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    (if: (⟨go.bool⟩! (![go.bool] "servGood"))
    then
      let: (("$ret0", "$ret1"), "$ret2") := (let: "$a0" := (![go.uint64] "servAddr") in
      let: "$a1" := (![cryptoffi.SigPublicKey] "servPk") in
      (FuncResolve auditor.New [] #()) "$a0" "$a1") in
      let: "$r0" := "$ret0" in
      let: "$r1" := "$ret1" in
      let: "$r2" := "$ret2" in
      do:  ("adtr2" <-[go.PointerType auditor.Auditor] "$r0");;;
      do:  ("adtr2Pk" <-[go.SliceType go.byte] "$r1");;;
      do:  ("err" <-[ktcore.Blame] "$r2");;;
      do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      do:  (let: "$a0" := (![go.uint64] (IndexRef (go.SliceType go.uint64) (![go.SliceType go.uint64] "adtrAddrs", #(W64 2)))) in
      (MethodResolve (go.PointerType advrpc.Server) "Serve"%go (let: "$a0" := (![go.PointerType auditor.Auditor] "adtr2") in
      (FuncResolve auditor.NewRpcAuditor [] #()) "$a0")) "$a0");;;
      do:  (let: "$a0" := time.Millisecond in
      (FuncResolve time.Sleep [] #()) "$a0")
    else do:  #());;;
    let: "alicePk2" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    let: "$r0" := (let: "$a0" := #(W64 32) in
    (FuncResolve cryptoffi.RandBytes [] #()) "$a0") in
    do:  ("alicePk2" <-[go.SliceType go.byte] "$r0");;;
    do:  (let: "$a0" := (![go.SliceType go.byte] "alicePk2") in
    (MethodResolve (go.PointerType client.Client) "Put"%go (![go.PointerType client.Client] "alice")) "$a0");;;
    do:  (let: "$a0" := (#(W64 2) *⟨time.Duration⟩ epochTime) in
    (FuncResolve time.Sleep [] #()) "$a0");;;
    let: (("$ret0", "$ret1"), "$ret2") := ((MethodResolve (go.PointerType client.Client) "SelfMon"%go (![go.PointerType client.Client] "alice")) #()) in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    let: "$r2" := "$ret2" in
    do:  ("ep" <-[go.uint64] "$r0");;;
    do:  ("isChanged" <-[go.bool] "$r1");;;
    do:  ("err" <-[ktcore.Blame] "$r2");;;
    do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    do:  (let: "$a0" := ((![go.uint64] "ep") =⟨go.uint64⟩ #(W64 2)) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    do:  (let: "$a0" := (![go.bool] "isChanged") in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    let: "bobPk2" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    let: "bobHasPk2" := (GoAlloc go.bool (GoZeroVal go.bool #())) in
    let: ((("$ret0", "$ret1"), "$ret2"), "$ret3") := (let: "$a0" := aliceUid in
    (MethodResolve (go.PointerType client.Client) "Get"%go (![go.PointerType client.Client] "bob")) "$a0") in
    let: "$r0" := "$ret0" in
    let: "$r1" := "$ret1" in
    let: "$r2" := "$ret2" in
    let: "$r3" := "$ret3" in
    do:  ("ep" <-[go.uint64] "$r0");;;
    do:  ("bobHasPk2" <-[go.bool] "$r1");;;
    do:  ("bobPk2" <-[go.SliceType go.byte] "$r2");;;
    do:  ("err" <-[ktcore.Blame] "$r3");;;
    do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    do:  (let: "$a0" := ((![go.uint64] "ep") =⟨go.uint64⟩ #(W64 2)) in
    (FuncResolve primitive.Assume [] #()) "$a0");;;
    (if: (⟨go.bool⟩! (![go.bool] "servGood"))
    then
      do:  ((MethodResolve (go.PointerType auditor.Auditor) "Update"%go (![go.PointerType auditor.Auditor] "adtr2")) #());;;
      let: "startEp" := (GoAlloc go.uint64 (GoZeroVal go.uint64 #())) in
      let: ((("$ret0", "$ret1"), "$ret2"), "$ret3") := (let: "$a0" := (![go.uint64] (IndexRef (go.SliceType go.uint64) (![go.SliceType go.uint64] "adtrAddrs", #(W64 2)))) in
      let: "$a1" := (![go.SliceType go.byte] "adtr2Pk") in
      (MethodResolve (go.PointerType client.Client) "Audit"%go (![go.PointerType client.Client] "alice")) "$a0" "$a1") in
      let: "$r0" := "$ret0" in
      let: "$r1" := "$ret1" in
      let: "$r2" := "$ret2" in
      let: "$r3" := "$ret3" in
      do:  ("startEp" <-[go.uint64] "$r0");;;
      do:  ("ep" <-[go.uint64] "$r1");;;
      do:  ("err" <-[ktcore.Blame] "$r2");;;
      do:  "$r3";;;
      do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      do:  (let: "$a0" := ((![go.uint64] "startEp") =⟨go.uint64⟩ #(W64 1)) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      do:  (let: "$a0" := ((![go.uint64] "ep") =⟨go.uint64⟩ #(W64 2)) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      let: ((("$ret0", "$ret1"), "$ret2"), "$ret3") := (let: "$a0" := (![go.uint64] (IndexRef (go.SliceType go.uint64) (![go.SliceType go.uint64] "adtrAddrs", #(W64 2)))) in
      let: "$a1" := (![go.SliceType go.byte] "adtr2Pk") in
      (MethodResolve (go.PointerType client.Client) "Audit"%go (![go.PointerType client.Client] "bob")) "$a0" "$a1") in
      let: "$r0" := "$ret0" in
      let: "$r1" := "$ret1" in
      let: "$r2" := "$ret2" in
      let: "$r3" := "$ret3" in
      do:  ("startEp" <-[go.uint64] "$r0");;;
      do:  ("ep" <-[go.uint64] "$r1");;;
      do:  ("err" <-[ktcore.Blame] "$r2");;;
      do:  "$r3";;;
      do:  (let: "$a0" := ((![ktcore.Blame] "err") =⟨ktcore.Blame⟩ ktcore.BlameNone) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      do:  (let: "$a0" := ((![go.uint64] "startEp") =⟨go.uint64⟩ #(W64 1)) in
      (FuncResolve primitive.Assume [] #()) "$a0");;;
      do:  (let: "$a0" := ((![go.uint64] "ep") =⟨go.uint64⟩ #(W64 2)) in
      (FuncResolve primitive.Assume [] #()) "$a0")
    else do:  #());;;
    do:  (let: "$a0" := (⟨go.bool⟩! (![go.bool] "bobHasPk0")) in
    (FuncResolve std.Assert [] #()) "$a0");;;
    do:  (let: "$a0" := (![go.bool] "bobHasPk1") in
    (FuncResolve std.Assert [] #()) "$a0");;;
    do:  (let: "$a0" := (let: "$a0" := (![go.SliceType go.byte] "bobPk1") in
    let: "$a1" := (![go.SliceType go.byte] "alicePk1") in
    (FuncResolve bytes.Equal [] #()) "$a0" "$a1") in
    (FuncResolve std.Assert [] #()) "$a0");;;
    do:  (let: "$a0" := (![go.bool] "bobHasPk2") in
    (FuncResolve std.Assert [] #()) "$a0");;;
    do:  (let: "$a0" := (let: "$a0" := (![go.SliceType go.byte] "bobPk2") in
    let: "$a1" := (![go.SliceType go.byte] "alicePk2") in
    (FuncResolve bytes.Equal [] #()) "$a0" "$a1") in
    (FuncResolve std.Assert [] #()) "$a0");;;
    return: #()).

#[global] Instance info' : PkgInfo pkg_id.alicebob :=
{|
  pkg_imported_pkgs := [code.bytes.pkg_id.bytes; code.time.pkg_id.time; code.github_com.goose_lang.primitive.pkg_id.primitive; code.github_com.goose_lang.std.pkg_id.std; code.github_com.sanjit_bhat.pav.auditor.pkg_id.auditor; code.github_com.sanjit_bhat.pav.client.pkg_id.client; code.github_com.sanjit_bhat.pav.cryptoffi.pkg_id.cryptoffi; code.github_com.sanjit_bhat.pav.ktcore.pkg_id.ktcore; code.github_com.sanjit_bhat.pav.server.pkg_id.server]
|}.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.alicebob (λ: <>,
      exception_do (do:  (server.initialize' #());;;
      do:  (ktcore.initialize' #());;;
      do:  (cryptoffi.initialize' #());;;
      do:  (client.initialize' #());;;
      do:  (auditor.initialize' #());;;
      do:  (std.initialize' #());;;
      do:  (primitive.initialize' #());;;
      do:  (time.initialize' #());;;
      do:  (bytes.initialize' #()))
      ).

Class Assumptions `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] testAliceBob_unfold :: FuncUnfold testAliceBob [] (testAliceBobⁱᵐᵖˡ);
  #[global] import_bytes_Assumption :: bytes.Assumptions;
  #[global] import_time_Assumption :: time.Assumptions;
  #[global] import_primitive_Assumption :: primitive.Assumptions;
  #[global] import_std_Assumption :: std.Assumptions;
  #[global] import_auditor_Assumption :: auditor.Assumptions;
  #[global] import_client_Assumption :: client.Assumptions;
  #[global] import_cryptoffi_Assumption :: cryptoffi.Assumptions;
  #[global] import_ktcore_Assumption :: ktcore.Assumptions;
  #[global] import_server_Assumption :: server.Assumptions;
}.
End alicebob.
