(* autogenerated from github.com/sanjit-bhat/pav/cryptoffi *)
Require Export New.code.crypto.ed25519.
Require Export New.code.github_com.sanjit_bhat.pav.cryptoffi.ffi.
From New.golang Require Import defn.
From New Require Import crypto_prelude.
Module pkg_id.
Definition cryptoffi : go_string := "github.com/sanjit-bhat/pav/cryptoffi".

End pkg_id.
Export pkg_id.
Module cryptoffi.

Definition Hasher {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/sanjit-bhat/pav/cryptoffi.Hasher"%go [].

#[global] Opaque Hasher.

Definition SigPrivateKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/sanjit-bhat/pav/cryptoffi.SigPrivateKey"%go [].

#[global] Opaque SigPrivateKey.

Definition SigPublicKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/sanjit-bhat/pav/cryptoffi.SigPublicKey"%go [].

#[global] Opaque SigPublicKey.

Definition VrfPrivateKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/sanjit-bhat/pav/cryptoffi.VrfPrivateKey"%go [].

#[global] Opaque VrfPrivateKey.

Definition VrfPublicKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.Named "github.com/sanjit-bhat/pav/cryptoffi.VrfPublicKey"%go [].

#[global] Opaque VrfPublicKey.

Axiom SigPrivateKeyⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom VrfPrivateKeyⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Axiom VrfPublicKeyⁱᵐᵖˡ : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, go.type.

Definition HashLen {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val := #(W64 32).

Definition NewHasher {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi.NewHasher"%go.

Definition SigGenerateKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi.SigGenerateKey"%go.

Definition VrfGenerateKey {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi.VrfGenerateKey"%go.

Definition VrfPublicKeyEncode {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi.VrfPublicKeyEncode"%go.

Definition VrfPublicKeyDecode {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi.VrfPublicKeyDecode"%go.

Definition RandBytes {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi.RandBytes"%go.

(* go: cryptoffi_model.go:21:6 *)
Definition NewHasherⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    exception_do (return: (GoAlloc Hasher (CompositeLiteral Hasher (LiteralValue [])))).

(* go: cryptoffi_model.go:25:19 *)
Definition Hasher__Writeⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "hr" "b",
    exception_do (let: "hr" := (GoAlloc (go.PointerType Hasher) "hr") in
    let: "b" := (GoAlloc (go.SliceType go.byte) "b") in
    let: "$r0" := (let: "$a0" := (![go.SliceType go.byte] (StructFieldRef Hasher "b"%go (![go.PointerType Hasher] "hr"))) in
    let: "$a1" := (![go.SliceType go.byte] "b") in
    (FuncResolve go.append [go.SliceType go.byte] #()) "$a0" "$a1") in
    do:  ((StructFieldRef Hasher "b"%go (![go.PointerType Hasher] "hr")) <-[go.SliceType go.byte] "$r0");;;
    return: #()).

(* go: cryptoffi_model.go:29:19 *)
Definition Hasher__Sumⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: "hr" "b",
    exception_do (let: "hash" := (GoAlloc (go.SliceType go.byte) (GoZeroVal (go.SliceType go.byte) #())) in
    let: "hr" := (GoAlloc (go.PointerType Hasher) "hr") in
    let: "b" := (GoAlloc (go.SliceType go.byte) "b") in
    return: (let: "$a0" := (![go.SliceType go.byte] "b") in
     let: "$a1" := (Convert go.string (go.SliceType go.byte) (let: "$a0" := (Convert (go.SliceType go.byte) go.string (![go.SliceType go.byte] (StructFieldRef Hasher "b"%go (![go.PointerType Hasher] "hr")))) in
     (FuncResolve ffi.TrustedHash [] #()) "$a0")) in
     (FuncResolve go.append [go.SliceType go.byte] #()) "$a0" "$a1")).

#[global] Instance info' : PkgInfo pkg_id.cryptoffi :=
{|
  pkg_imported_pkgs := [code.crypto.ed25519.pkg_id.ed25519; code.github_com.sanjit_bhat.pav.cryptoffi.ffi.pkg_id.ffi]
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.cryptoffi (λ: <>,
      exception_do (do:  (ffi.initialize' #());;;
      do:  (ed25519.initialize' #()))
      ).

Module Hasher.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Record t :=
mk {
  b' : slice.t;
}.

#[global] Instance zero_val : ZeroVal t := {| zero_val := mk (zero_val _)|}.
#[global] Arguments mk : clear implicits.
#[global] Arguments t : clear implicits.
End def.
End Hasher.

Definition Hasher'fds_unsealed {ext : ffi_syntax} {go_gctx : GoGlobalContext} : list go.field_decl := [
  (go.FieldDecl "b"%go (go.SliceType go.byte))
].
Program Definition Hasher'fds {ext : ffi_syntax} {go_gctx : GoGlobalContext} := sealed (Hasher'fds_unsealed).
Global Instance equals_unfold_Hasher {ext : ffi_syntax} {go_gctx : GoGlobalContext} : Hasher'fds =→ Hasher'fds_unsealed.
Proof. rewrite /Hasher'fds seal_eq //. Qed.

Definition Hasherⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := go.StructType (Hasher'fds).

Class Hasher_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Hasher_type_repr  :: go.TypeReprUnderlying Hasherⁱᵐᵖˡ Hasher.t;
  #[global] Hasher_underlying :: (Hasher) <u (Hasherⁱᵐᵖˡ);
  #[global] Hasher_get_b (x : Hasher.t) :: ⟦StructFieldGet (Hasherⁱᵐᵖˡ) "b", #x⟧ ⤳[under] #x.(Hasher.b');
  #[global] Hasher_set_b (x : Hasher.t) y :: ⟦StructFieldSet (Hasherⁱᵐᵖˡ) "b", (#x, #y)⟧ ⤳[under] #(x <|Hasher.b' := y|>);
  #[global] Hasher'ptr_Sum_unfold :: MethodUnfold (go.PointerType (Hasher)) "Sum" (Hasher__Sumⁱᵐᵖˡ);
  #[global] Hasher'ptr_Write_unfold :: MethodUnfold (go.PointerType (Hasher)) "Write" (Hasher__Writeⁱᵐᵖˡ);
}.

Module SigPrivateKey.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End SigPrivateKey.

Class SigPrivateKey_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SigPrivateKey_type_repr  :: go.TypeReprUnderlying SigPrivateKeyⁱᵐᵖˡ SigPrivateKey.t;
  #[global] SigPrivateKey_underlying :: (SigPrivateKey) <u (SigPrivateKeyⁱᵐᵖˡ);
  #[global] SigPrivateKeyⁱᵐᵖˡ_underlying :: (SigPrivateKeyⁱᵐᵖˡ) ↓u (SigPrivateKeyⁱᵐᵖˡ);
}.

Module SigPublicKey.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Definition t : Type := ed25519.PublicKey.t.
#[global] Arguments t : clear implicits.
End def.
End SigPublicKey.

Definition SigPublicKeyⁱᵐᵖˡ {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go.type := ed25519.PublicKey.

Class SigPublicKey_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] SigPublicKey_underlying :: (SigPublicKey) <u (SigPublicKeyⁱᵐᵖˡ);
}.

Module VrfPrivateKey.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End VrfPrivateKey.

Class VrfPrivateKey_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] VrfPrivateKey_type_repr  :: go.TypeReprUnderlying VrfPrivateKeyⁱᵐᵖˡ VrfPrivateKey.t;
  #[global] VrfPrivateKey_underlying :: (VrfPrivateKey) <u (VrfPrivateKeyⁱᵐᵖˡ);
  #[global] VrfPrivateKeyⁱᵐᵖˡ_underlying :: (VrfPrivateKeyⁱᵐᵖˡ) ↓u (VrfPrivateKeyⁱᵐᵖˡ);
}.

Module VrfPublicKey.
Section def.
Context {ext : ffi_syntax} {go_gctx : GoGlobalContext}.
Axiom t : Type.
Axiom zero_val : ZeroVal t.
#[global] Existing Instance zero_val.
End def.
End VrfPublicKey.

Class VrfPublicKey_Assumptions {ext : ffi_syntax} `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] VrfPublicKey_type_repr  :: go.TypeReprUnderlying VrfPublicKeyⁱᵐᵖˡ VrfPublicKey.t;
  #[global] VrfPublicKey_underlying :: (VrfPublicKey) <u (VrfPublicKeyⁱᵐᵖˡ);
  #[global] VrfPublicKeyⁱᵐᵖˡ_underlying :: (VrfPublicKeyⁱᵐᵖˡ) ↓u (VrfPublicKeyⁱᵐᵖˡ);
}.

Class Assumptions `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] Hasher_instance :: Hasher_Assumptions;
  #[global] SigPrivateKey_instance :: SigPrivateKey_Assumptions;
  #[global] SigPublicKey_instance :: SigPublicKey_Assumptions;
  #[global] VrfPrivateKey_instance :: VrfPrivateKey_Assumptions;
  #[global] VrfPublicKey_instance :: VrfPublicKey_Assumptions;
  #[global] NewHasher_unfold :: FuncUnfold NewHasher [] (NewHasherⁱᵐᵖˡ);
  #[global] import_ed25519_Assumption :: ed25519.Assumptions;
  #[global] import_ffi_Assumption :: ffi.Assumptions;
}.
End cryptoffi.
