(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.crypto_prelude.
Require Export New.generatedproof.bytes.
Require Export New.generatedproof.github_com.goose_lang.primitive.
Require Export New.generatedproof.github_com.goose_lang.std.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.auditor.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.client.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.cryptoffi.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.ktcore.
Require Export New.generatedproof.github_com.sanjit_bhat.pav.server.
Require Export New.generatedproof.time.
Require Export New.golang.theory.
Require Export New.code.github_com.sanjit_bhat.pav.alicebob.

Set Default Proof Using "Type".

Module alicebob.
End alicebob.
