(* autogenerated by goose proofgen; do not modify *)
Require Export New.proof.crypto_prelude.
Require Export New.manualproof.github_com.sanjit_bhat.pav.cryptoffi.ffi.
Require Export New.golang.theory.
Require Export New.code.github_com.sanjit_bhat.pav.cryptoffi.ffi.

Set Default Proof Using "Type".

Module ffi.
End ffi.
