(* autogenerated from github.com/sanjit-bhat/pav/cryptoffi/ffi *)
From New.golang Require Import defn.
Require Export New.trusted_code.github_com.sanjit_bhat.pav.cryptoffi.ffi.
Import ffi.
From New Require Import crypto_prelude.
Module pkg_id.
Definition ffi : go_string := "github.com/sanjit-bhat/pav/cryptoffi/ffi".

End pkg_id.
Export pkg_id.
Module ffi.

Definition TrustedHash {ext : ffi_syntax} {go_gctx : GoGlobalContext} : go_string := "github.com/sanjit-bhat/pav/cryptoffi/ffi.TrustedHash"%go.

#[global] Instance info' : PkgInfo pkg_id.ffi :=
{|
  pkg_imported_pkgs := []
|}.

Axiom _'init : ∀ {ext : ffi_syntax} {go_gctx : GoGlobalContext}, val.

Definition initialize' {ext : ffi_syntax} {go_gctx : GoGlobalContext} : val :=
  λ: <>,
    package.init pkg_id.ffi (λ: <>,
      exception_do (do:  #())
      ).

Class Assumptions `{!GoGlobalContext} `{!GoLocalContext} `{!GoSemanticsFunctions} : Prop :=
{
  #[global] TrustedHash_unfold :: FuncUnfold TrustedHash [] (TrustedHashⁱᵐᵖˡ);
}.
End ffi.
