name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    # every Monday at 9am UTC (4am EST).
    - cron: '0 9 * * 1'

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: go test -v -skip=Bench ./...

  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: go vet ./...
      - run: gofmt -w -s . && git diff --exit-code
      - run: go fix ./... && git diff --exit-code
      - name: compiled RPC
        run: |
          go run ./serde --in ktcore/serde.go && git diff --exit-code
          go run ./serde --in merkle/serde.go && git diff --exit-code
          go run ./serde --in auditor/serde.go && git diff --exit-code

  goose:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: go tool perennial-cli goose && git diff --exit-code

  proof:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: proof
    steps:
      - uses: actions/checkout@v6
      - name: Install Rocq
        uses: tchajed/setup-rocq@v1
        with:
          rocq-version: 9.1
      - name: Install deps
        run: |
          opam pin add --no-action .
          opam install --deps-only .
      - name: Rocq build
        run: make -j4
      - run: opam install --assume-built .
      - run: opam uninstall .
